apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-4
  labels:
    app: project4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project4
  template:
    metadata:
      labels:
        app: project4
    spec:
      containers:
      - name: project-4
        image: 657224673055.dkr.ecr.us-east-1.amazonaws.com/project4:latest
        imagePullPolicy: Always
        ports:
          - name: app
            containerPort: 80
      imagePullSecrets:
          - name: key